# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Continuos Integration with Git Hub Actions

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
    # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
    #  Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven (Build Application Jar)
      working-directory: ./rest-whit-spring-and-java-erudio/rest-whit-spring-and-java-erudio
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./rest-whit-spring-and-java-erudio
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: | 
         docker tag ${{ secrets.DOCKER_USERNAME }}/rest-whit-spring-and-java-erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest-whit-spring-and-java-erudio:${{ github.run_id }}
         
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-whit-spring-and-java-erudio:${{ github.run_id }}
         docker push ${{ secrets.DOCKER_USERNAME }}/rest-whit-spring-and-java-erudio:latest
        
      env:
        GITHUB_TOKEN: ${{ github.token }}
